apiVersion: v1
kind: Service
metadata:
  name: linksapp-lb
spec:
  type: LoadBalancer
  #Selector to match target Pods
  selector:
    run: linksapp
  ports:
  - protocol: TCP
    port: 80
    targetPort: 4000