apiVersion: v1
kind: Service
metadata:
  name: linksapp
spec:
  type: ClusterIP
  #Selector to match target Pods
  selector:
    run: linksapp
  ports:
  - protocol: TCP
    port: 4000
    targetPort: 4000