apiVersion: v1
data:
  db.sql: "CREATE DATABASE IF NOT EXISTS linksdb;\n\nUSE linksdb;\n\n-- TABLE USER\n--
    all pasword wil be encrypted using SHA2\nCREATE TABLE users (\n  id INT(11) NOT
    NULL AUTO_INCREMENT,\n  fullname VARCHAR(100) NOT NULL,\n  email VARCHAR(100)
    NOT NULL,\n  password VARCHAR(60) NOT NULL,\n  created_at timestamp NOT NULL DEFAULT
    CURRENT_TIMESTAMP,\n  PRIMARY KEY (id)\n) AUTO_INCREMENT=2;\n\n-- drop table users\n\nDESCRIBE
    users;\n\nINSERT INTO users (id, email, password, fullname) \n  VALUES (1, 'john',
    'john@gmail.com', 'John Carter');\n\nSELECT * FROM users;\n\n-- LINKS TABLE\nCREATE
    TABLE links (\n  id INT(11) NOT NULL,\n  title VARCHAR(150) NOT NULL,\n  url VARCHAR(255)
    NOT NULL,\n  description TEXT,\n  user_id INT(11),\n  created_at timestamp NOT
    NULL DEFAULT current_timestamp,\n  CONSTRAINT fk_user FOREIGN KEY(user_id) REFERENCES
    users(id)\n);\n\nALTER TABLE links\n  ADD PRIMARY KEY (id);\n\nALTER TABLE links\n
    \ MODIFY id INT(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT = 2;\n\nDESCRIBE links;"
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: linksapp-schema
